### ISSUE TITLE
Endlose Restarts seit 1.4.1

### ISSUE THREAD

**Issue by smaragdschlange** [smaragdschlange/ioBroker.nuki#42]
Seit Update 1.4.1 habe ich folgendes Problem: auch mit dem Update heute auf 1.4.2 
IO Broker startet Endlos.

Hier das LOG:
`host.iobroker       2020-11-19 17:20:53.587 info       Restart adapter system.adapter.nuki.0 because enabled
host.iobroker       2020-11-19 17:20:53.586   info   instance system.adapter.nuki.0 terminated with code 0 (NO_ERROR)
nuki.0 2020-11-19 17:20:53.066   info   (1651) Terminated (NO_ERROR): Without reason
nuki.0 2020-11-19 17:20:53.065   info   (1651) terminating
nuki.0 2020-11-19 17:20:53.047   info   (1651) cleaned everything up...
nuki.0 2020-11-19 17:20:53.045   error at IncomingMessage.emit (events.js:326:22)
nuki.0 2020-11-19 17:20:53.045   error at Object.onceWrapper (events.js:420:28)
nuki.0 2020-11-19 17:20:53.045   error at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12)
nuki.0 2020-11-19 17:20:53.045   error at Request.emit (events.js:314:20)
nuki.0 2020-11-19 17:20:53.045   error at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10)
nuki.0 2020-11-19 17:20:53.045   error at Request.emit (events.js:314:20)
nuki.0 2020-11-19 17:20:53.045   error at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
nuki.0 2020-11-19 17:20:53.045   error at Request._callback (/opt/iobroker/node_modules/iobroker.nuki/main.js:1237:17)
nuki.0 2020-11-19 17:20:53.045   error at updateAllLockStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:868:13)
nuki.0 2020-11-19 17:20:53.045   error at initNukiDeviceStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:366:19)
nuki.0 2020-11-19 17:20:53.045   error (1651) TypeError: Cannot read property 'hasOwnProperty' of undefined
nuki.0 2020-11-19 17:20:53.043   error (1651) uncaught exception: Cannot read property 'hasOwnProperty' of undefined
nuki.0 2020-11-19 17:20:53.030   info   (1651) Lock list requested: http://192.168.1.211:8080/list?ts=2020-11-19T16:20:52Z&rnr=27&hash=8d4adfbb1867f7b3f7226da55f96ffd617b477873796070bbf58ffbe0be42a35
nuki.0 2020-11-19 17:20:50.033   info   (1651) Bridge Info requested: http://192.168.1.211:8080/info?ts=2020-11-19T16:20:49Z&rnr=25221&hash=6a03fa0219a1393eb33f628427a8e5fd68302623692392d7b653ba29b9a704d9
nuki.0 2020-11-19 17:20:46.845   info   (1651) starting. Version 1.4.1 in /opt/iobroker/node_modules/iobroker.nuki, node: v12.19.1, js-controller: 3.1.6
host.iobroker       2020-11-19 17:20:45.339   info   instance system.adapter.nuki.0 started with pid 1651`

Keine Ahnung warum das so ist, aber das Problem besteht leider weiterhin. Habe eben ein Rallback auf 1.3.1 gemacht, da läuft der Stabil ohne Endlosrestarts

Lg
Wing_Stefan (IOBroker Forum)

**Comment by smaragdschlange** [comment]
Hi Stefan,
Könntest Du mir bitte noch Deine Nuki Smartlock Version und die Firmware Version nennen? Hast Du eine Harware- oder Software-Bridge? Was kommt zurück, wenn Du im Browser http://192.168.1.211:8080/list?token=[token] ([token] durch Deinen Token austauschen) eingibst?

Gruß
Sven

**Comment by smaragdschlange** [comment]
Hallo Sven,
Hier das Ergebnis vom Link:
[{"deviceType": 0, "nukiId": 609044532, "name": "Haustür", "firmwareVersion": "2.9.10", "lastKnownState": {"mode": 2, "state": 3, "stateName": "unlocked", "batteryCritical": false, "batteryCharging": false, "batteryChargeState": 100, "doorsensorState": 2, "doorsensorStateName": "door closed", "timestamp": "2020-11-26T09:28:56+00:00"}}, {"deviceType": 0, "nukiId": 447706221, "name": "Garagentür"}]

Firmware 2.9.10 – gestern gabs auch hier ein Update
Nuki Smartlock 2.0 mit Nuki Bridge HW. (die White Edition die es kürzlich gab, also HW habe ich jetzt ca. 2-3 Wochen.

LG
Stefan

**Comment by smaragdschlange** [comment]
Hi Stefan,
was ist denn das 2. Device in dem Response mit dem Namen "Garagentür"? Laut DeviceType handelt es sich auch um ein Nuki Smartlock, aber es wird gar kein "lastKnownState" empfangen. Das könnte den beschriebenen Fehler verursachen. Existiert dieses Schloss wirklich, oder ist das noch ein Überbleibsel? Wenn das Schloss gar nicht existiert, lösche bitte die Verknüpfung der Bridge mit dem Smartlock "Garagentür".

Gruß
Sven

**Comment by smaragdschlange** [comment]
Hallo Sven,

ja die gibt es, war die alte schwarze Smart Lock 2.0. Diese hätte ich vorgehabt in der Garage bei der Seitentüre anzubringen, leider passt diese noch nicht, derzeit liegt diese ohne Batterien herum. Kann sie aber derzeit mal löschen, da wie gesagt ich sie nicht anbringen kann und bei Bedarf eben wieder neu verbinden. Werde nach dem löschen, den Nuki Adapter aktualisieren, mal sehen wie er dann läuft. Melde mich danach wieder wie es aussieht.

Danke vorerst.

Lg

**Comment by smaragdschlange** [comment]
Hallo Sven,

bin früher dazugekommen.
Sieht ganz gut aus, anfangs habe ich noch vergessen den auch direkt auf der Bridge zu entfernen. Weil nur in der App und auf der Website bringt nichts, da hat ers immer noch unter Objekte gefunden.
Also auf der Bridge entfernt , alle Objekte vom Nuki im iobroker entfernt und Adapter gestartet, seitdem war das die letzte Meldung und bis jetzt kein endlos restart.
Das heißt für mich wenn ein Gerät offline ist, muss ich es entfernen da sonst der Adapter immer restartet und danach sucht..

Okay danke für die Hilfe.
