### ISSUE TITLE
uncaught exception jscontroller 3.3.13

### ISSUE THREAD

**Issue by Ilovegym66** [smaragdschlange/ioBroker.nuki#50]
Hi,
mit 3.3.13 läuft bei mir der Nuki nicht mehr, Node 14.17.0, NPM 6.14.4:

```
2021-06-20 10:58:16.571  - debug: nuki.0 (65253) Redis Objects: Use Redis connection: 127.0.0.1:6379
2021-06-20 10:58:16.590  - debug: nuki.0 (65253) Objects client ready ... initialize now
2021-06-20 10:58:16.591  - debug: nuki.0 (65253) Objects create System PubSub Client
2021-06-20 10:58:16.592  - debug: nuki.0 (65253) Objects create User PubSub Client
2021-06-20 10:58:16.592  - debug: nuki.0 (65253) Objects client initialize lua scripts
2021-06-20 10:58:16.599  - debug: nuki.0 (65253) Objects connected to redis: 127.0.0.1:6379
2021-06-20 10:58:16.603  - debug: nuki.0 (65253) objectDB connected
2021-06-20 10:58:16.604  - debug: nuki.0 (65253) Redis States: Use Redis connection: 127.0.0.1:6379
2021-06-20 10:58:16.608  - debug: nuki.0 (65253) States create System PubSub Client
2021-06-20 10:58:16.609  - debug: nuki.0 (65253) States create User PubSub Client
2021-06-20 10:58:16.613  - debug: nuki.0 (65253) States connected to redis: 127.0.0.1:6379
2021-06-20 10:58:16.613  - debug: nuki.0 (65253) statesDB connected
2021-06-20 10:58:16.751  - info: nuki.0 (65253) starting. Version 1.4.4 in /opt/iobroker/node_modules/iobroker.nuki, node: v14.17.0, js-controller: 3.3.13
2021-06-20 10:58:16.771  - debug: nuki.0 (65253) config Nuki bridge name: Nuki bridge
2021-06-20 10:58:16.772  - debug: nuki.0 (65253) config IP address: 192.168.0.30
2021-06-20 10:58:16.772  - debug: nuki.0 (65253) config port: 8080
2021-06-20 10:58:16.772  - debug: nuki.0 (65253) config token: xxxx
2021-06-20 10:58:16.773  - debug: nuki.0 (65253) timer set: 60000 milliseconds
2021-06-20 10:58:16.571  - debug: nuki.0 (65253) Redis Objects: Use Redis connection: 127.0.0.1:6379
2021-06-20 10:58:16.590  - debug: nuki.0 (65253) Objects client ready ... initialize now
2021-06-20 10:58:16.591  - debug: nuki.0 (65253) Objects create System PubSub Client
2021-06-20 10:58:16.592  - debug: nuki.0 (65253) Objects create User PubSub Client
2021-06-20 10:58:16.592  - debug: nuki.0 (65253) Objects client initialize lua scripts
2021-06-20 10:58:16.599  - debug: nuki.0 (65253) Objects connected to redis: 127.0.0.1:6379
2021-06-20 10:58:16.603  - debug: nuki.0 (65253) objectDB connected
2021-06-20 10:58:16.604  - debug: nuki.0 (65253) Redis States: Use Redis connection: 127.0.0.1:6379
2021-06-20 10:58:16.608  - debug: nuki.0 (65253) States create System PubSub Client
2021-06-20 10:58:16.609  - debug: nuki.0 (65253) States create User PubSub Client
2021-06-20 10:58:16.613  - debug: nuki.0 (65253) States connected to redis: 127.0.0.1:6379
2021-06-20 10:58:16.613  - debug: nuki.0 (65253) statesDB connected
2021-06-20 10:58:16.751  - info: nuki.0 (65253) starting. Version 1.4.4 in /opt/iobroker/node_modules/iobroker.nuki, node: v14.17.0, js-controller: 3.3.13
2021-06-20 10:58:16.771  - debug: nuki.0 (65253) config Nuki bridge name: Nuki bridge
2021-06-20 10:58:16.772  - debug: nuki.0 (65253) config IP address: 192.168.0.30
2021-06-20 10:58:16.772  - debug: nuki.0 (65253) config port: 8080
2021-06-20 10:58:16.772  - debug: nuki.0 (65253) config token: xxxx
2021-06-20 10:58:16.773  - debug: nuki.0 (65253) timer set: 60000 milliseconds
2021-06-20 10:58:18.709  - info: synology.0 (49626) State value to set for "synology.0.DiskStationManager.info.uptime" has to be type "string" but received type "number"
2021-06-20 10:58:18.709  - info: synology.0 (49626) State value to set for "synology.0.DiskStationManager.vol_info.volume_1.used_size" has to be type "number" but received type "string"
2021-06-20 10:58:18.709  - info: synology.0 (49626) State value to set for "synology.0.DiskStationManager.info.uptime" has to be type "string" but received type "number"
2021-06-20 10:58:18.709  - info: synology.0 (49626) State value to set for "synology.0.DiskStationManager.vol_info.volume_1.used_size" has to be type "number" but received type "string"
2021-06-20 10:58:20.054  - info: tuya.0 (54857) State value to set for "tuya.0.bf88c2fc494909d538nhnf.21" has to be type "number" but received type "string"
2021-06-20 10:58:20.214  - info: nuki.0 (65253) Bridge Info requested: http://192.168.0.30:8080/info?token=xxxxx
2021-06-20 10:58:20.225  - info: nuki.0 (65253) State value to set for "nuki.0.164400993.info.timestamp" has to be type "string" but received type "object"
2021-06-20 10:58:20.054  - info: tuya.0 (54857) State value to set for "tuya.0.bf88c2fc494909d538nhnf.21" has to be type "number" but received type "string"
2021-06-20 10:58:20.214  - info: nuki.0 (65253) Bridge Info requested: http://192.168.0.30:8080/info?token=sl0ufi
2021-06-20 10:58:20.225  - info: nuki.0 (65253) State value to set for "nuki.0.164400993.info.timestamp" has to be type "string" but received type "object"
2021-06-20 10:58:22.882  - info: nuki.0 (65253) Lock list requested: http://192.168.0.30:8080/list?token=xxxx
2021-06-20 10:58:22.883  - debug: nuki.0 (65253) found Nuki device: 279997633
2021-06-20 10:58:22.886  - debug: nuki.0 (65253) found Nuki device: 645032813
2021-06-20 10:58:22.887  - error: nuki.0 (65253) uncaught exception: Cannot read property 'hasOwnProperty' of undefined
2021-06-20 10:58:22.888  - error: nuki.0 (65253) TypeError: Cannot read property 'hasOwnProperty' of undefined
    at initNukiDeviceStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:366:19)
    at updateAllLockStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:868:13)
    at Request._callback (/opt/iobroker/node_modules/iobroker.nuki/main.js:1237:17)
    at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:376:20)
    at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:482:28)
    at IncomingMessage.emit (events.js:388:22)
2021-06-20 10:58:22.888  - error: nuki.0 (65253) Cannot read property 'hasOwnProperty' of undefined
2021-06-20 10:58:22.897  - info: nuki.0 (65253) cleaned everything up...
2021-06-20 10:58:22.897  - info: nuki.0 (65253) terminating
2021-06-20 10:58:22.898  - warn: nuki.0 (65253) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-06-20 10:58:22.900  - info: nuki.0 (65253) State value to set for "nuki.0.279997633.info.deviceType" has to be type "string" but received type "number"
2021-06-20 10:58:22.900  - info: nuki.0 (65253) State value to set for "nuki.0.279997633.info.mode" has to be type "string" but received type "number"
2021-06-20 10:58:22.882  - info: nuki.0 (65253) Lock list requested: http://192.168.0.30:8080/list?token=xxxxx
2021-06-20 10:58:22.883  - debug: nuki.0 (65253) found Nuki device: 279997633
2021-06-20 10:58:22.886  - debug: nuki.0 (65253) found Nuki device: 645032813
2021-06-20 10:58:22.887  - error: nuki.0 (65253) uncaught exception: Cannot read property 'hasOwnProperty' of undefined
2021-06-20 10:58:22.888  - error: nuki.0 (65253) TypeError: Cannot read property 'hasOwnProperty' of undefined
    at initNukiDeviceStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:366:19)
    at updateAllLockStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:868:13)
    at Request._callback (/opt/iobroker/node_modules/iobroker.nuki/main.js:1237:17)
    at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:376:20)
    at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:482:28)
    at IncomingMessage.emit (events.js:388:22)
2021-06-20 10:58:22.888  - error: nuki.0 (65253) Cannot read property 'hasOwnProperty' of undefined
2021-06-20 10:58:22.897  - info: nuki.0 (65253) cleaned everything up...
2021-06-20 10:58:22.897  - info: nuki.0 (65253) terminating
2021-06-20 10:58:22.898  - warn: nuki.0 (65253) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-06-20 10:58:22.900  - info: nuki.0 (65253) State value to set for "nuki.0.279997633.info.deviceType" has to be type "string" but received type "number"
2021-06-20 10:58:22.900  - info: nuki.0 (65253) State value to set for "nuki.0.279997633.info.mode" has to be type "string" but received type "number"
2021-06-20 10:58:23.913  - error: host.VMC123-iobroker instance system.adapter.nuki.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-06-20 10:58:23.915  - info: host.VMC123-iobroker Restart adapter system.adapter.nuki.0 because enabled
2021-06-20 10:58:23.913  - error: host.VMC123-iobroker instance system.adapter.nuki.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-06-20 10:58:23.915  - info: host.VMC123-iobroker Restart adapter system.adapter.nuki.0 because enabled

```

**Comment by smaragdschlange** [comment]
Hi,
ich habe jetzt die Version 1.5.0 auf GitHub (noch nicht als latest Version im npm) und habe meinen jscontroller auf Version 3.3.13 gebracht. Ich bekomme keinen Abbruch, habe aber auch erst Version 12.22.1 von Node.js. Bitte teste doch trotzdem mal diese Version und schau, ob Dein Problem gefixt ist.

Gruß Sven

**Comment by Ilovegym66** [comment]
Hi,
super, Danke, funktioniert, der Fehler ist weg.
Dankeschön!
Gruss, 
Bernd
