### ISSUE TITLE
Mit js-controller 6.0.1-alpha läuft die Instanz nicht

### ISSUE THREAD

**Issue by Brainbug01** [smaragdschlange/ioBroker.nuki#76]
Core adapters versions
js-controller:  6.0.1-alpha.0-20240525-56d9e4a2e
admin:          6.17.14
javascript:     8.4.0

``
2024-05-26 16:07:53.657	info	Do not restart adapter system.adapter.nuki.0 because disabled or deleted
host.iobroker
2024-05-26 16:07:53.657	error	instance system.adapter.nuki.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker
2024-05-26 16:07:53.657	error	Caught by controller[0]: Node.js v20.13.1
host.iobroker
2024-05-26 16:07:53.657	error	Caught by controller[0]: at node:internal/main/run_main_module:28:49
host.iobroker
2024-05-26 16:07:53.657	error	Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
host.iobroker
2024-05-26 16:07:53.657	error	Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:1024:12)
host.iobroker
2024-05-26 16:07:53.657	error	Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1208:32)
host.iobroker
2024-05-26 16:07:53.657	error	Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
host.iobroker
2024-05-26 16:07:53.657	error	Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1358:14)
host.iobroker
2024-05-26 16:07:53.657	error	Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.nuki/main.js:1601:5)
host.iobroker
2024-05-26 16:07:53.657	error	Caught by controller[0]: at startAdapter (/opt/iobroker/node_modules/iobroker.nuki/main.js:51:15)
host.iobroker
2024-05-26 16:07:53.657	error	Caught by controller[0]: TypeError: utils.Adapter is not a constructor
host.iobroker
2024-05-26 16:07:53.657	error	Caught by controller[0]: ^
host.iobroker
2024-05-26 16:07:53.656	error	Caught by controller[0]: adapter = new utils.Adapter(options);
host.iobroker
2024-05-26 16:07:53.656	error	Caught by controller[0]: /opt/iobroker/node_modules/iobroker.nuki/main.js:51
``

**Comment by mcm1957** [comment]
Update adapter-core to 3.1.4 should fix this

Adding @iobroker/testing 4.1.3 is also required. See other issue

**Comment by Horgul123** [comment]
@smaradschlage Updates all adapters and iobroler itself to latest beta versions, issue still exists

**Comment by Brainbug01** [comment]
@Horgul123 
Momentan kannst du nur ausweichen auf den nuki.extended Adapter oder zurück zum stable 5.0.19

**Comment by mcm1957** [comment]
Bitte den Adapter nuki-extended ansehen / verwenden.

**Comment by Horgul123** [comment]
Werd ich wohl machen müssen :) Danke für den Hinweis.

**Comment by simatec** [comment]
I have made a PR on the known problems... Let's see if the developer releases it...
https://github.com/smaragdschlange/ioBroker.nuki/pull/78

**Comment by Speedbreaker12** [comment]
Bitte nicht den Nuki Extended, ich habe 100 skripte die alle den hier benutzen, da die struktur im Extended super unübersichtlich sind. Bin jetzt wieder auf 5.0.19 zurück. Ich würde mich super freuen, wenn man diesen hier mit der 6 zum laufen bekommen würde.

**Comment by Brainbug01** [comment]
@Speedbreaker12 
Wie viele Schlösser hast du von Nuki?
Ich hab nur ein Schloss und hatte mir schon länger Alias angelegt. Der Wechsel war in ein paar Minuten erledigt, 3 Datenpunkte neu verbinden.

**Comment by simatec** [comment]
> Bitte nicht den Nuki Extended, ich habe 100 skripte die alle den hier benutzen, da die struktur im Extended super unübersichtlich sind. Bin jetzt wieder auf 5.0.19 zurück. Ich würde mich super freuen, wenn man diesen hier mit der 6 zum laufen bekommen würde.

Wenn du magst, kannst du mal meine Änderungen für js-controller 6.0.x testen. Musst du über Github mit folgenden Link installieren:

https://github.com/simatec/ioBroker.nuki.git

**Comment by Horgul123** [comment]
@simatec Wird das dann quasi einfach über den "offiziellen" nuki (nicht extended) Adapter installiert und alles läuft wie bisher?

**Comment by simatec** [comment]
ja das ist zum testen kein Problem...

**Comment by Horgul123** [comment]
@simatec Ah klasse. Installation hat geklappt und es scheint auf den ersten Blick zu laufen. Dank Dir für die Anpassung!

**Comment by Speedbreaker12** [comment]
> > Bitte nicht den Nuki Extended, ich habe 100 skripte die alle den hier benutzen, da die struktur im Extended super unübersichtlich sind. Bin jetzt wieder auf 5.0.19 zurück. Ich würde mich super freuen, wenn man diesen hier mit der 6 zum laufen bekommen würde.
> 
> Wenn du magst, kannst du mal meine Änderungen für js-controller 6.0.x testen. Musst du über Github mit folgenden Link installieren:
> 
> https://github.com/simatec/ioBroker.nuki.git

Läuft wie am Schnürchen! Vielen Dank! Da hast du mir wirklich sehr geholfen.

**Comment by smaragdschlange** [comment]
Hi,
mit den Fixes von @simatec, die ich in der neuesten Version 2.0.0 veröffentlicht habe ist der Adapter auch mit js-controller 6.0.4 funktionsfähig.

Gruß
Sven
